#!/usr/bin/env python2.5

"""
usage: bdr-getform <recording> <formula_id>
"""

import os
import re
import sys
import getopt
import gdbm


def getFormula(recordDir, id):
   formPath = recordDir + "/form.gdbm"
   db = gdbm.open(formPath, 'r')

   formula = db[id]
   print formula

   db.close()

def usage(code, msg=''):
   print __doc__
   if msg: print msg
   sys.exit(code)

def main():
   try:
      opts, args = getopt.getopt(sys.argv[1:], '',
            [
               ])
   except getopt.error, msg:
      usage(2, msg)

   if len(args) != 2:
      usage('Must specify recording.')

   recordDir = args[0]

   getFormula(recordDir, args[1])

main()
