#! /bin/bash 

NO_ARGS=0
ERROR=255
if [[ $# -lt $NO_ARGS ]]
then 
	echo "Usage:$0 -n <NODES>" && exit $ERROR
fi

while getopts ":n:h" Option
do
	case $Option in
		n) NODES=$OPTARG;;
		h) echo "Usage:$0 -n <NODES> " && exit 0;;
	esac
done

if  ls -1d exp.* &>/dev/null
then
	if [ -z $NODES ]
	then 
		NODES=`ls -1d exp.*|wc -l`
	fi
else
	exit $ERROR
fi
COUNT=0
for((i=0;i<NODES;i=i+1,COUNT++));do 
	START=`head -1 exp.$i-*/log*`
	END=`tail -1 exp.$i-*/log*`
	if [[ ! -z "$START" && ! -z "$END" ]];
	then
		START=`echo $START|awk 'BEGIN {FS=":| |[[]|[]]"} {printf "%d:%d:%d", $2,$3,$4}'`
		printf "%d\t$START\t$END\n" $COUNT;
	fi
done


